name: ReqRes API CI/CD

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Create reports folder
        run: mkdir -p reports

      - name: Create timestamp
        run: echo "REPORT_TIME=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV

      - name: Run ReqRes Functional Suite
        run: |
          newman run collections/ReqRes_Collection.json \
          -e environments/QA_Environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export reports/reqres_${{ env.REPORT_TIME }}.html

      - name: Run E2E Chaining Tests
        run: |
          newman run collections/E2E_User_Chaining.json \
          -e environments/QA_Environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export reports/e2e_${{ env.REPORT_TIME }}.html

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports-${{ env.REPORT_TIME }}
          path: reports/